### ISSUE TITLE
jetmetHelperRun2.py not working with isFastSim=True 2016 and 2017

### ISSUE THREAD

**Issue by bartokm** [cms-nanoAOD/nanoAOD-tools#208] opened 2019-11-05 13:43 UTC
When using createJMECorrector with isFastSim=True, and dataYear=2016 or dataYear=2017, it gives the following error message:

> %MSG-e JetCorrectorParameters: 
> No definitions found!!!

2018 is working fine!

**Comment by danbarto** [comment] 2019-11-05 14:12
Can you provide how you call creatJMECorrector exactly? I can't reproduce your issue.

**Comment by bartokm** [comment] 2019-11-05 15:37
I've found out that the problem is only with AK8 jets. The 2016 and 2017 .tgz files doesn't have the AK8 part. In the official twiki I see they're included:
https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC

**Comment by danbarto** [comment] 2019-11-05 16:22
Thanks for reporting that, I'm currently fixing the tarballs. Note though that there are no AK8PFPuppi corrections available for 2016 FastSim.

**Comment by fgolf** [comment] 2019-11-06 21:57
This issue is addressed by PR #211 for all available corrections.

**Closed by fgolf** 2019-11-06 21:57 UTC
