### ISSUE TITLE
Dropping branches for output module makes them unavailable for computations in other modules

### ISSUE THREAD

**Issue by vasile-ghete** [cms-nanoAOD/nanoAOD-tools#35] opened 2018-01-12 08:43 UTC
If branches are dropped in keep_and_drop.txt, they are not available for computations in other modules.

How to test:

In keep_and_drop.txt, add
 'drop Electron_*',
 'drop Muon_*',

then run lepMerger. 

In all events, there will be no leptons at all in the collection Lepton, even if there are electrons and muons in the corresponding collections. To make the things worse, this is a silent behaviour, no message is written (ROOT...) 

Correct behaviour would be to have the commands from keep_and_drop.txt applied to the output module only.

**Comment by vasile-ghete** [comment] 2018-01-12 08:46
Of course, it is
drop Electron_*
drop Muon_*

**Comment by arizzi** [comment] 2018-03-06 16:07
@rappoccio  was this fixed by one of your PRs? can we close?

**Comment by rappoccio** [comment] 2018-03-07 11:33
I think so. I am traveling this week so unable to do any derailed testing but I think my latest updates should fix this.

**Comment by vasile-ghete** [comment] 2018-03-07 13:55
I am testing if using outputbranchsel solves the problem; but it seems now it does not drop anything from the output tree, using branchsel=None and the directives to keep and drop in outputbranchsel. I need more testing and to look at Sal changes...

**Comment by rappoccio** [comment] 2018-03-15 13:43
@vasile-ghete OK, coming back to this, I'm not sure I understand the problem or the symptoms (or, how to reproduce). Can you give me a specific recipe and what you expect to see?

**Comment by rappoccio** [comment] 2018-03-15 17:47
Right, that feature should be there, but @vasile-ghete is experiencing trouble, I think...

**Comment by arizzi** [comment] 2018-03-16 14:36
mhh I think @vasile-ghete is right that it cannot work this way but there is no need for double copy.

We can do as suggested by @lenzip here
https://github.com/latinos/LatinoAnalysis/blob/master/Gardener/python/gardening.py#L104-L119

i.e.  we change
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/output.py#L64
so that we first set to 1 only the OUTPUT branches, then we clone, then we set to 1 also the other branches .

anyone willing to give it a try and make a PR?

**Comment by vasile-ghete** [comment] 2018-03-16 16:18
@arizzi I can look at it only next Tuesday afternoon - if nobody else does it till then...

**Comment by vasile-ghete** [comment] 2018-03-23 13:04
I made a PR with the proposed solution to drop branches in the output only.

branchsel is now used to disable branches in the input tree which are known to not be used by any module in the computation.

outputbranchsel keep/drop branches in the output tree, independently of branchsel. outputbranchsel is applied also for fullClone.

I did not implement a cross-check of branchsel and outputbranchsel, so the user must be careful to not drop in branchsel branches which are kept in outputbranchsel.

Also, I did not test yet the changes with friendTree, but there is no interference between the changes to FullOutput and FriendOutput, so it should be OK. I will do it eventually, just to be sure.

Not related to this, I added the logger to collectionMerger module, to be able to debug it on request only (logger level DEBUG). I dislike print, logger has many advantages. The module calling the collection merger should have the appropriate code to use the logger, otherwise the logger from collectionMerger is inactive.

**Comment by vasile-ghete** [comment] 2018-04-20 12:25
I created a minimal PR to fix the problem of output branches. 
https://github.com/cms-nanoAOD/nanoAOD-tools/pull/74

**Comment by vasile-ghete** [comment] 2018-04-25 07:57
This issue is more than three months old, a fix to the bug was provided more than one month ago, another PR was made again as the first PR was no more compatible. What prevents to merge the PR and fix the bug?
The bug is major, especially considering the (pseudo)-"friendliness" of ROOT which does not give an error, but set to zero the branch which is dropped and use it with the wrong value.

**Comment by arizzi** [comment] 2018-04-27 11:56
nanoAOD-tools is not a production system, neither requires large recompile... so having a feature not merged doesn't imply that it cannot be used

Now the fact that the PR changes the style of the constructors because that is what the PR authors like most is probably what held it so far... plus I didn't have time to test it myself.. and it seems also the other maintainers didn't

**Closed** 2018-05-03 09:04 UTC
